name: Local Node CI Test

on:
  push:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  node-tests:
    uses: ./.github/workflows/nodejs-test-lint.yaml
    with:
      working-directory: 'testdata/nodejs'
      node-version: '22'
      test-flags: 'run'
      eslint-flags: '.'
