name: Local Python CI Test

on:
  push:

jobs:
  python-tests:
    uses: ./.github/workflows/python-test-lint.yaml
    with:
      working-directory: 'testdata/python'
      python-version: '3.13.7'
      requirements-file: 'requirements.txt'
      disable-linter: false
